export const TOPBAR_HEIGHT = 30;
export const CLIP_HEIGHT = 80;
export const MIN_GRID_HEIGHT = 2000;
export const SCROLLBAR_HEIGHT = 30;
export const TRACK_PANEL_WIDTH = 200;
export const TRACK_NUMBER_WIDTH = 25;
export const TRACK_PANEL_FULL_WIDTH = TRACK_PANEL_WIDTH + TRACK_NUMBER_WIDTH;
